Phosphor/instrumentJRE.sh

Fixes the errors (`IOException (error = 0)/(error=2))` that arise when trying to run subprocesses with `ProcessBuilder`.

add chmod +x to jre/bin/, jre/lib/, fixes issues with subprocess running

---

Phosphor/src/edu/columbia/cs/psl/phosphor/TaintUtils.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/LocalVariableManager.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/PopOptimizingMV.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/PrimitiveArrayAnalyzer.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/TaintTrackingClassVisitor.java

This pull request is focused on resolving occurrences of Sonar rule 
squid:S2864 - "entrySet()" should be iterated when both the key and value are needed.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2864
Please let me know if you have any questions.
Faisal Hameed

Code quality fix - "entrySet()" should be iterated when both the key and value are needed.

---

Phosphor/src/edu/columbia/cs/psl/phosphor/Configuration.java
Phosphor/src/edu/columbia/cs/psl/phosphor/TaintUtils.java

This pull request is focused on resolving occurrences of Sonar rule 
squid:S1125 - Literal boolean values should not be used in condition expressions. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1125
Please let me know if you have any questions.
Faisal Hameed

Code quality fix - Literal boolean values should not be used in condition expressions.

---

Phosphor/src/edu/columbia/cs/psl/phosphor/Instrumenter.java
Phosphor/src/edu/columbia/cs/psl/phosphor/TaintUtils.java
Phosphor/src/edu/columbia/cs/psl/phosphor/struct/DoubleLinkedList.java
Phosphor/src/edu/columbia/cs/psl/phosphor/struct/LinkedList.java

This pull request is focused on resolving occurrences of Sonar rule 
squid:S1149 - Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1149
Please let me know if you have any questions.
Faisal Hameed

Code quality fix - Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used.

---

Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/BoxedPrimitiveStoreWithIntTags.java
Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/BoxedPrimitiveStoreWithObjTags.java

This pull request is focused on resolving occurrences of Sonar rule 
squid:S2153 - Boxing and unboxing should not be immediately reversed.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2153
Please let me know if you have any questions.
Faisal Hameed

Code quality fix - Boxing and unboxing should not be immediately reversed.

---

Phosphor/instrumentJRE.sh

When I run `mvn verify`, there is a warning:
`OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0`
Remove this option in the shell script.

remove option MaxPermSize=512m

---

Phosphor/src/edu/columbia/cs/psl/phosphor/BasicSourceSinkManager.java

If a test application code does not contain the sink methods in a taint-sink file which is used by phosphor to instrument the applications code, a lot of exceptions would be thrown. This fix is for that.

Fix for taint sinks

---

Phosphor/src/edu/columbia/cs/psl/phosphor/Instrumenter.java

At present, Phosphor cannot instrument .war file correctly, if .war file contains .jar file. This fix is for that.

instrument .war file correctly

---

Phosphor/test/edu/columbia/cs/psl/test/phosphor/RuntimeAnnotationExample.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/RuntimeAnnotationImplicitITCase.java

This just *crashes* -- so I'm not sure how it gets picked up in the unit tests or what convention you are using for that since the other tests look like the assume a working Phosphor. 
If you let me know what you do in this case I'll add it. If you run with: 
```
mvn verify -P integration-test-implicit-tracking
```
You'll see the crash near the end.

added test case for runtime annotation problem.

---

Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/analyzer/InstMethodSinkInterpreter.java

The original version of the code lumped them with instructions
such as FADD, which take two arguments of the same type (e.g.,
float in the case of FADD) and return a result of the same type.
For LCMP, DCMPL, DCMPG, FCMPL and FCMPG, this is incorrect: While they
take two arguments of identical type, they always return an int.
This pull request fixes this by making these five opcodes return the correct type.

Fix return type of LCMP/[DF]CMP[LG] instructions.

---

Phosphor/src/edu/columbia/cs/psl/phosphor/Configuration.java
Phosphor/src/edu/columbia/cs/psl/phosphor/Instrumenter.java
Phosphor/src/edu/columbia/cs/psl/phosphor/PreMain.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/TaintPassingMV.java

The implementation is guarded by an option -withoutBranchNotTaken.

Implemented disabling the branch not taken in control tracking

---

Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/CharacterUtils.java

I instrumented Lucene with int-tags and got the following error:
```
Exception in thread "main" java.lang.NoSuchMethodError: edu.columbia.cs.psl.phosphor.runtime.CharacterUtils.toChars$$PHOSPHORTAGGED(IILedu/columbia/cs/psl/phosphor/struct/LazyCharArrayIntTags;[CIILedu/columbia/cs/psl/phosphor/struct/TaintedIntWithIntTag;)Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithIntTag;
at org.apache.lucene.analysis.CharacterUtils.toLowerCase$$PHOSPHORTAGGED(CharacterUtils.java:58)
at org.apache.lucene.analysis.LowerCaseFilter.incrementToken$$PHOSPHORTAGGED(LowerCaseFilter.java:45)
at org.apache.lucene.analysis.FilteringTokenFilter.incrementToken$$PHOSPHORTAGGED(FilteringTokenFilter.java:49)
at org.apache.lucene.index.DefaultIndexingChain$PerField.invert$$PHOSPHORTAGGED(DefaultIndexingChain.java: …
```

Added missing CharacterUtils method

---

Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/Taint.java

Setting a taint in a string in Taint.combineTagsOnObject was only setting the String.PHOSPHOR_TAG field, not calling the set method. This behavior caused the taint to be missed at a sink. The missed taint occurred in TaintSourceWrapper.checkTaint(Object obj, String sink) at line 194. The conditional checks for String.valuePHOSPHOR_TAG, which was not changed when tainting and object in Taint.combineTagsOnObject.

fixed how to set the taint in a string

---

Phosphor/.gitignore
Phosphor/test/edu/columbia/cs/psl/test/phosphor/AutoTaintObjTagITCase.java

Fails with NPE before merging @katherine-hough changes. This took a while primarily because I wanted to step through the test in Intellij prior to making this PR.
There are some .gitignore improvements as an extra incentive!

Integration Test to confirm TaintThrough handles non-tainted obj case.

---

Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/TaintTrackingClassVisitor.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/LambdaObjTagITCase.java

Added check that newArgs is not empty before calling newArgs.getLast to prevent a NoSuchElementException when checking for lambdas with a void return with a pre-allocated return obj passed to them. Added test case that was failing prior to this change.

Added check that newArgs is not empty before calling newArgs.getLast

---

Phosphor/src/edu/columbia/cs/psl/phosphor/BasicSourceSinkManager.java
Phosphor/src/edu/columbia/cs/psl/phosphor/Instrumenter.java
Phosphor/src/edu/columbia/cs/psl/phosphor/NullSourceSinkManager.java
Phosphor/src/edu/columbia/cs/psl/phosphor/SourceSinkManager.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/SinkTaintingMV.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/SourceTaintingMV.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/TaintThroughTaintingMV.java
Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/TaintSourceWrapper.java

* Changed checkTaint for Taint tags to pass the associated primitive value
* Added getBaseSink to SourceSinkManager which returns the name of the original sink method from which a particular sink inherited its status as a sink.
* Refactored TaintSourceWrapper.autoTaint also changed how it handles tainting TaintedWithObjTag objects
* Changed various sink methods to pass the a string for the base sink in additional to the actual sink being called

TaintSourceWrapper autoTaint and checkTaint changes

---

Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/Taint.java

Fixed issue where a Taint's lbl could be added to its dependencies. Switched various tests for label equivalence from using == to using equals method. Standardized brackets and spacing. Minor refactoring.

Taint duplicate label fix

---

Phosphor/src/edu/columbia/cs/psl/phosphor/BasicSourceSinkManager.java
Phosphor/src/edu/columbia/cs/psl/phosphor/PreMain.java
Phosphor/src/edu/columbia/cs/psl/phosphor/SourceSinkTransformer.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/OgnlUtilCV.java

Made it possible to replace the base set of sources, sinks, and taintThrough methods used in auto-tainting at runtime. Refactored BasicSourceSinkManager.

Replace auto taint methods

---

Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/MultiTainter.java
Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/NativeHelper.java
Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/Taint.java
Phosphor/src/edu/columbia/cs/psl/phosphor/struct/LazyArrayIntTags.java
Phosphor/src/edu/columbia/cs/psl/phosphor/struct/LazyArrayObjTags.java
Phosphor/test/edu/columbia/cs/psl/phosphor/struct/LazyArrayIntTagsTest.java
Phosphor/test/edu/columbia/cs/psl/phosphor/struct/LazyArrayObjTagsTest.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/ArrayOptimizationIntTagITCase.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/ArrayOptimizationObjTagITCase.java

Quick code changes to two abstract classes with two unit tests as well.

LazyArrayObjTags and LazyArrayIntTags equals and hashcode use underlying val field

---

Phosphor/src/edu/columbia/cs/psl/phosphor/TaintUtils.java
Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/ReflectionMasker.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/ReflectionObjTagITCase.java

* Fixed issue with ReflectionMasker.getOrigMethod(Constructor m, boolean isObjTags) incorrectly remapping arguments
* Added previously failing test cases to demonstrate prior issues with ReflectionMasker.getOrigMethod(Constructor m, boolean isObjTags)

Fixed issues with ReflectionMasker.getOrigMethod

---

Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/ReflectionHidingMV.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/TaintTrackingClassVisitor.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/UninstrumentedReflectionHidingMV.java
Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/ReflectionMasker.java
Phosphor/src/edu/columbia/cs/psl/phosphor/struct/SinglyLinkedList.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/ReflectionObjTagITCase.java

* Made the hashCode methods added by phosphor to classes synthetic
* Changed ReflectionMasker to hide synthetic hashCode and equals methods for Class.getDeclaredMethods and to replace them for Class.getMethods
* Added previously failing test case to check that equals and hashCode methods added by phosphor are hidden  when calling Class.getDeclaredMethods
* Added previously failing test case to check that equals and hashCode methods added by phosphor are replaced by Object.equals and Object.hashCode when calling Class.getMethods

Hide added hash code

---

Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/ReflectionMasker.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/runtime/FieldHolderBaseTest.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/runtime/MethodHolder.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/runtime/MethodReflectionImplicitITCase.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/runtime/MethodReflectionObjTagITCase.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/runtime/PrimitiveSupplier.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/runtime/ReflectionObjTagITCase.java

* Added tests that Class.getDeclaredMethod and Class.getMethod do not return synthetic equals and hashCode methods added by Phosphor
* Masked Class.getDeclaredMethod and Class.getMethod to ensure that they do not return synthetic equals and hashCode methods added by Phosphor
* Changed "masking" of getMethod to match getDeclaredMethod
* Fixes #124

* Refactored method reflection tests

---

Phosphor/src/edu/columbia/cs/psl/phosphor/PreMain.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/SerializationFixingCV.java
Phosphor/src/edu/columbia/cs/psl/phosphor/instrumenter/TaintTrackingClassVisitor.java
Phosphor/src/edu/columbia/cs/psl/phosphor/runtime/BoxedPrimitiveStoreWithObjTags.java
Phosphor/src/edu/columbia/cs/psl/phosphor/struct/SerializationWrapper.java
Phosphor/src/edu/columbia/cs/psl/phosphor/struct/WeakIdentityHashMap.java
Phosphor/src/edu/columbia/cs/psl/phosphor/struct/multid/MultiDTaintedArray.java
Phosphor/test/edu/columbia/cs/psl/phosphor/util/IgnoredTestUtil.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/GetSetTaintObjTagITCase.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/runtime/SerializationImplicitITCase.java
Phosphor/test/edu/columbia/cs/psl/test/phosphor/runtime/SerializationObjTagITCase.java

* Fixed issues with keeping taint tag when serializing primitives and boxed primitives (fixes #123)
* "Added" tests for serialization with implicit tracking enabled
* Fixed issue with serialization with implicit tracking where Phosphor tries to incorrectly unwrap primitive array wrapper before call to native method NativeMethodAccessorImpl.invoke0 but method being invoked is the writeObject or readObject method for the primitive wrapper type
* Changed BoxedPrimitiveStoreWithObjTags to use a WeakIdentityHashMap to prevent store tags for Bytes/Booleans/Characters/Shorts with the same value from being overwritten
* Added tests that reveal prior issue with BoxedPrimitiveStoreWithObjTags overwriting tags for Bytes/Booleans/Characters/Shorts with the same value

Boxing and Serialization fixes

---

Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/runtime/ReflectionMasker.java

This PR is to solve the #150 . If current method is tainted method, we just return the original parameter list when `addTypeParams`.

#150 add sanity check to avoid addTypeParams to tainted methods

---

Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/runtime/CharacterUtils.java
integration-tests/src/test/java/edu/columbia/cs/psl/test/phosphor/CharacterCodePointObjTagITCase.java

According to the document: `codePointBefore` returns the char at index-1 (https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Character.html#codePointBefore(char%5B%5D,int)).
This PR fixes the issue and adds a new integration test.

Fix off by 1 error in codePointBefore

---

Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/SerializationFixingCV.java
phosphor-instrument-jigsaw/src/main/java/edu/columbia/cs/psl/jigsaw/phosphor/instrumenter/JLinkInvoker.java
phosphor-instrument-jigsaw/src/main/java/module-info.java

This PR fixes two issues when custom class visitors or tag factories are provided. 
1.  Skip `SerializationFixingCV` if stream classes are ignored by `taintTagFactory`.
2. Fix classpath and module issues while using `jlink` with custom class visitors.

Fix crashes when custom class visitors and tag factories are provided.

---

integration-tests/src/test/java/edu/columbia/cs/psl/test/phosphor/ArrayArgWrapperObjTagITCase.java

This PR fixes the object leaking when a non-instrumented method is called. It basically removes the optimization that does not update argWrapper when the top of the stack is null. Another solution is to check if the callee is instrumented. I'm not sure about the performance impact of this optimization. If it is negligible I feel this solution is better than adding additional checks to the callee.
A new test case is attached.
The `pom.xml` update helps me to build phosphor on Ubuntu and the `StandaloneJVMInstrumenter` update fixes an NPE. I'm happy to revert this change if it breaks your build.
Test: mvn verify

Fix object leaking through argWrapper 

---

phosphor-instrument-jigsaw/pom.xml
phosphor-instrument-jigsaw/src/main/java/edu/columbia/cs/psl/jigsaw/phosphor/instrumenter/StandaloneJVMInstrumenter.java

- Fix missing dependency while building phosphor on Ubuntu
- Fix NPE while passing args to StandaloneJVMInstrumenter

Fix NPE and compilation issues.

---

Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/LocalVariableManager.java

I saw `com.sun.jdi.InconsistentDebugInfoException` exception when I attach the debugger to an instrumented application. The exception is caused by inconsistent scope information for shadow variables. This PR makes the shadow variable have the same scope information as the original local variable. 
I don't have a good integration test for this since the exception is thrown by my debugger. I use the following test case and verify the debugger works correctly after the fix. 
```java
import edu.columbia.cs.psl.phosphor.runtime.MultiTainter;
public class TestDebug {
public static void print(String a, String b, String c, String d) {
if (check()) {
String s0 = MultiTainter.taintedReference(null, "123");
System.out.println(MultiTainter.getTaint(s0));
}
if (check()) {
String s1 = null; …
```

Fix local variable table labels for added variables.

---

Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/Instrumenter.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/ConfigurationEmbeddingMV.java

As discussed in #182, we want to update Configuration values while embedding them into JDK.  This PR implements `ConfigurationEmbeddingMV` that iterates and updates public fields in Configuration.

Add ConfigurationEmbeddingMV to embed Configuration values.

---

Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/PreMain.java

The `TaintTrackingClassVisitor` adds an invisible annotation to the class file https://github.com/gmu-swe/phosphor/blob/9ac22f5252468e6fb619c1bc69624fa30fec19e5/Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/TaintTrackingClassVisitor.java#L189. Therefore, we should check `invisibleAnnotations` instead of `visitbleAnnotations`.

Terminate instrumentation when TaintInstrumented annotation is found.

---

Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/ReflectionHidingMV.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/TaintMethodRecord.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/TaintTrackingClassVisitor.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/runtime/PhosphorStackFrame.java
integration-tests/src/test/java/edu/columbia/cs/psl/test/phosphor/LambdaObjTagITCase.java

This PR fixes issue #188 with these changes:
* Ensure that, when an unwrapped object is passed to an unistrumented wrapper (to a parameter of type java.lang.Object), that the object is wrapped before passing to the instrumented code. Exclude "Unsafe" from this handling, as it is necessary to still be able to use putReference etc. to set an underlying field
* For @CallerSensitive methods, collect the callerClass in the uninstrumented wrapper and pass it into the instrumented code

Fixes Issue 188 - Crashes around MethodHandleImpl

---

Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/TaintTrackingClassVisitor.java

Some program may crash because the mismatched modifiers. So we should not modify them unless in debug mode. 
https://github.com/kleben/jersey/blob/master/core-common/src/main/java/org/glassfish/jersey/internal/inject/JerseyClassAnalyzer.java#L219

Only modify the modifiers in debug mode

---

.github/workflows/main.yml
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/BasicSourceSinkManager.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/Instrumenter.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/PhosphorPatcher.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/InstrumentedJREProxyGenerator.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/ReflectionHidingMV.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/TaintAdapter.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/TaintMethodRecord.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/TaintPassingMV.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/TaintTrackingClassVisitor.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/UninstrumentedCompatMV.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/runtime/PhosphorStackFrame.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/runtime/TaintSourceWrapper.java
phosphor-instrument-jigsaw/src/main/java/edu/columbia/cs/psl/jigsaw/phosphor/instrumenter/PhosphorJLinkPlugin.java
phosphor-instrument-jigsaw/src/main/java/edu/columbia/cs/psl/jigsaw/phosphor/instrumenter/PhosphorPacker.java
pom.xml

* Removed double declaration of compiler plugin from aggregator POM.
* Factored packing of Phosphor into java.base module out of PhosphorJLinkPlugin into new class PhosphorPacker.
* Factored patching of Phosphor class from Instrumenter into new class PhosphorPatcher.
* Fixed issue with missing Unsafe#put/getReference methods in Java 11 causing JVM to crash.
* Fixed issue with intrinsic Unsafe#put/getObject methods in Java 11 causing JVM to crash.
* Fixed circular class loading in Java 11 from use of ConcurrentHashMap in BasicSourceSinkManager.
* Fixed tag loss related to VarHandles in Java 11 by patching the descriptor for the frame's hash.
* Added Java 11 to GHA workflow matrix.
* Increased version of checkout action in GHA workflow to v3.
* Added no -ntp (--no-transfer-progress) flag to …

Java 11 Fixes

---

Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/PhosphorPatcher.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/instrumenter/TaintMethodRecord.java
Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/struct/TaggedReferenceArray.java
integration-tests/src/test/java/edu/columbia/cs/psl/test/phosphor/AnnotationInstCase.java

Phosphor instrumentation throws an `IllegalArgumentException` when processing a class containing an annotation with a value of an `Enum` type.
```
java.lang.IllegalArgumentException: value edu.columbia.cs.psl.phosphor.struct.TaggedReferenceArray@770d3326
at java.base/edu.columbia.cs.psl.phosphor.org.objectweb.asm.SymbolTable.addConstant(SymbolTable.java:525)
at java.base/edu.columbia.cs.psl.phosphor.org.objectweb.asm.AnnotationWriter.visit(AnnotationWriter.java:259)
at java.base/edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.AnnotationNode.accept(AnnotationNode.java:226)
at java.base/edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.AnnotationNode.accept(AnnotationNode.java:193)
at java.base/edu.columbia.cs.psl.phosphor.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:674) …
```

Fixed failure when instrumenting classes with an annotation containing an Enum-type value
